version: '3.8'

services:
  # 1. DEBT COLLECTOR (PROMETHEUS)
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # 2. LAYAR TV (GRAFANA) - Updated Config!
  grafana:
    image: grafana/grafana:latest
    # Kita matikan port public-nya, biar cuma bisa diakses lewat Nginx
    # ports: 
    #   - "3000:3000" 
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      # Settingan biar Grafana sadar dia ada di folder /monitor
      - GF_SERVER_ROOT_URL=http://localhost:8000/monitor
      - GF_SERVER_SERVE_FROM_SUB_PATH=true

  # 3. POLISI LALU LINTAS (NGINX) - NEW MEMBER!
  nginx:
    image: nginx:latest
    ports:
     - "8000:80"  # <--- Ganti jadi 8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Masukkan buku peraturan tadi
    extra_hosts:
      - "host.docker.internal:host-gateway" # Biar Nginx bisa kontak K8s di laptop
    depends_on:
      - grafana # Nginx baru nyala kalau Grafana udah siap